//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ventana.Properties {
    using System;
    using System.Drawing;


    /// <summary>
    ///   Clase de recurso fuertemente tipado, para buscar cadenas traducidas, etc.
    /// </summary>
    // StronglyTypedResourceBuilder generó automáticamente esta clase
    // a través de una herramienta como ResGen o Visual Studio.
    // Para agregar o quitar un miembro, edite el archivo .ResX y, a continuación, vuelva a ejecutar ResGen
    // con la opción /str o recompile su proyecto de VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        internal static Image estrella_llena;
        internal static Image estrella_vacia;
        internal static Image estrella_media;
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Devuelve la instancia de ResourceManager almacenada en caché utilizada por esta clase.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ventana.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Reemplaza la propiedad CurrentUICulture del subproceso actual para todas las
        ///   búsquedas de recursos mediante esta clase de recurso fuertemente tipado.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _06b0c73865bff17afebd3591874cc9a7_Bundle_HArmor_rog_stor181_Splash {
            get {
                object obj = ResourceManager.GetObject("06b0c73865bff17afebd3591874cc9a7-Bundle_HArmor_rog_stor181_Splash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _390395ce5a4898831f908cb7a30334b4_ba909e21fa91171dbf7d8b05150c20a2 {
            get {
                object obj = ResourceManager.GetObject("390395ce5a4898831f908cb7a30334b4-ba909e21fa91171dbf7d8b05150c20a2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4d1180e592869543e75486faa4eb9d23 {
            get {
                object obj = ResourceManager.GetObject("4d1180e592869543e75486faa4eb9d23", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4J538SP3ZKNO1476725822156 {
            get {
                object obj = ResourceManager.GetObject("4J538SP3ZKNO1476725822156", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap _4J538SP3ZKNO14767258221561 {
            get {
                object obj = ResourceManager.GetObject("4J538SP3ZKNO14767258221561", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a0cecc53a16715c279ab3c6e4243c72d_6257affb4c2be3f02ab38771393278ab {
            get {
                object obj = ResourceManager.GetObject("a0cecc53a16715c279ab3c6e4243c72d-6257affb4c2be3f02ab38771393278ab", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap a330f9fecc388ce67f87b09855480ca3 {
            get {
                object obj = ResourceManager.GetObject("a330f9fecc388ce67f87b09855480ca3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Battlenet_logo {
            get {
                object obj = ResourceManager.GetObject("Battlenet-logo", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap blizzard_entertainment {
            get {
                object obj = ResourceManager.GetObject("blizzard-entertainment", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap COD_VG_CODE_Gift_Honor_Pack_Bnet_Product_Browsing_Card_960x540 {
            get {
                object obj = ResourceManager.GetObject("COD-VG-CODE-Gift-Honor-Pack-Bnet-Product_Browsing_Card-960x540", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Diablo_IV_Vessel_of_Hatred {
            get {
                object obj = ResourceManager.GetObject("Diablo IV Vessel of Hatred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overwatch {
            get {
                object obj = ResourceManager.GetObject("Overwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Overwatch_logo_1800x1277 {
            get {
                object obj = ResourceManager.GetObject("Overwatch_logo_1800x1277", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OW2_2023_Invasion_Bundle_BNET_1P_SA01_card_feature {
            get {
                object obj = ResourceManager.GetObject("OW2_2023_Invasion-Bundle_BNET_1P_SA01-card_feature", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OW2_2024_S13_UBP_BNET_SA01_SHOP_productasset_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("OW2_2024_S13-UBP-BNET_SA01_SHOP-productasset_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OW2_2024_S13_UBP_BNET_SA01_SHOP_productasset_1920x10801 {
            get {
                object obj = ResourceManager.GetObject("OW2_2024_S13-UBP-BNET_SA01_SHOP-productasset_1920x10801", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap OW2_S12_MythicWeaponSkin_Ana_BNET_Shop_ProductAssetGallery_1920x1080 {
            get {
                object obj = ResourceManager.GetObject("OW2_S12_MythicWeaponSkin_Ana_BNET_Shop_ProductAssetGallery_1920x1080", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoDiabloIV {
            get {
                object obj = ResourceManager.GetObject("VideoDiabloIV", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoHearthstone {
            get {
                object obj = ResourceManager.GetObject("VideoHearthstone", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoOverwatch {
            get {
                object obj = ResourceManager.GetObject("VideoOverwatch", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap VideoWorld_of_Warcraft {
            get {
                object obj = ResourceManager.GetObject("VideoWorld of Warcraft", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Busca un recurso adaptado de tipo System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Warcraft_Rumble {
            get {
                object obj = ResourceManager.GetObject("Warcraft Rumble", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
